/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ats.frontend.AdminStuff;

import ats.frontend.ATSFrontEnd;
import ats.frontend.ATSReportView;
import ats.frontend.DBInter;

import ats.frontend.Login;
import static ats.frontend.Login.db;
import ats.frontend.MainGUI;
import ats.frontend.ManageBlanks;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.security.CodeSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author armor
 */
public class AdminGUI extends javax.swing.JPanel {
    

    /**
     * Creates new form AdminGUI
     */
    
    
    DBInter db = Login.db;
    
    public AdminGUI() {
        initComponents();
        maintainAdvisorsGUI1.setVisible(false);
        restoreBackupGUI1.setVisible(false);
        agencyDetailsGUI1.setVisible(false);
        jLabel1.setText("Welcome "+MainGUI.userName);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addBlanksButton = new javax.swing.JButton();
        backupM = new javax.swing.JButton();
        backupR = new javax.swing.JButton();
        editAgency = new javax.swing.JButton();
        stockTurnoverRepo = new javax.swing.JButton();
        advisorEdit = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        blankType = new javax.swing.JComboBox<>();
        blankAmount = new javax.swing.JTextField();
        typeText = new javax.swing.JLabel();
        blankAmountText = new javax.swing.JLabel();
        assignBlanks = new javax.swing.JButton();
        blankTypeAssign = new javax.swing.JComboBox<>();
        blankAmountAssign = new javax.swing.JTextField();
        blankTypeText = new javax.swing.JLabel();
        blankAmountTextAssign = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        searchBox = new javax.swing.JTextField();
        find = new javax.swing.JButton();
        maintainAdvisorsGUI1 = new ats.frontend.AdminStuff.MaintainAdvisorsGUI();
        addBlanksButton1 = new javax.swing.JButton();
        blankAmount1 = new javax.swing.JTextField();
        blankAmountText1 = new javax.swing.JLabel();
        restoreBackupGUI1 = new ats.frontend.AdminStuff.RestoreBackupGUI();
        agencyDetailsGUI1 = new ats.frontend.AdminStuff.AgencyDetailsGUI();
        blankSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<Admin's name here>>");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });

        addBlanksButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addBlanksButton.setText("Add Blanks");
        addBlanksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBlanksButtonActionPerformed(evt);
            }
        });

        backupM.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backupM.setText("Manual Backup");
        backupM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupMActionPerformed(evt);
            }
        });

        backupR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backupR.setText("Restore Backup");
        backupR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupRActionPerformed(evt);
            }
        });

        editAgency.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        editAgency.setText("Edit Agency Details");
        editAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAgencyActionPerformed(evt);
            }
        });

        stockTurnoverRepo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stockTurnoverRepo.setText("Stock Turnover Report");
        stockTurnoverRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTurnoverRepoActionPerformed(evt);
            }
        });

        advisorEdit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        advisorEdit.setText("Maintrain Staff");
        advisorEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advisorEditActionPerformed(evt);
            }
        });

        logOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        blankType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "444", "440", "420", "201", "101", "451", "452" }));

        blankAmount.setBackground(new java.awt.Color(0, 0, 0));
        blankAmount.setForeground(new java.awt.Color(255, 255, 255));
        blankAmount.setText("0");
        blankAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                blankAmountFocusGained(evt);
            }
        });
        blankAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankAmountActionPerformed(evt);
            }
        });

        typeText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeText.setForeground(new java.awt.Color(255, 255, 255));
        typeText.setText("Type");

        blankAmountText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blankAmountText.setForeground(new java.awt.Color(255, 255, 255));
        blankAmountText.setText("Amount");

        assignBlanks.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        assignBlanks.setText("Assign Blanks");
        assignBlanks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBlanksActionPerformed(evt);
            }
        });

        blankTypeAssign.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "444", "440", "420", "201", "101", "451", "452" }));

        blankAmountAssign.setBackground(new java.awt.Color(0, 0, 0));
        blankAmountAssign.setForeground(new java.awt.Color(255, 255, 255));
        blankAmountAssign.setText("0");
        blankAmountAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankAmountAssignActionPerformed(evt);
            }
        });

        blankTypeText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blankTypeText.setForeground(new java.awt.Color(255, 255, 255));
        blankTypeText.setText("Type");

        blankAmountTextAssign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blankAmountTextAssign.setForeground(new java.awt.Color(255, 255, 255));
        blankAmountTextAssign.setText("Amount");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Username", "Name", "Requested Blanks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        searchBox.setText("Search");
        searchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBoxFocusGained(evt);
            }
        });
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        find.setText("Find");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        addBlanksButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addBlanksButton1.setText("Remove Blanks");
        addBlanksButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBlanksButton1ActionPerformed(evt);
            }
        });

        blankAmount1.setBackground(new java.awt.Color(0, 0, 0));
        blankAmount1.setForeground(new java.awt.Color(255, 255, 255));
        blankAmount1.setText("0000");
        blankAmount1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                blankAmount1FocusGained(evt);
            }
        });
        blankAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankAmount1ActionPerformed(evt);
            }
        });

        blankAmountText1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blankAmountText1.setForeground(new java.awt.Color(255, 255, 255));
        blankAmountText1.setText("Batch No.");

        blankSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        blankSearch.setText("Search Blank");
        blankSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("                    ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(addBlanksButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(blankAmount)
                                    .addComponent(blankType, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeText)
                                    .addComponent(blankAmountText, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editAgency)
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addBlanksButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(blankAmountText1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(blankAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(restoreBackupGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blankSearch)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(stockTurnoverRepo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(backupR)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(backupM)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(advisorEdit)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agencyDetailsGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(find))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(blankAmountAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(assignBlanks)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(blankTypeAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(blankTypeText)
                                                .addComponent(blankAmountTextAssign))
                                            .addGap(61, 61, 61)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maintainAdvisorsGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(logOut)
                                .addGap(27, 27, 27)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(find)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(assignBlanks)
                                    .addComponent(blankTypeAssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blankTypeText))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blankAmountAssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blankAmountTextAssign))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(maintainAdvisorsGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logOut)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editAgency)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                                .addComponent(restoreBackupGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(agencyDetailsGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addBlanksButton)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(blankType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(blankAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(typeText)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(blankAmountText)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addBlanksButton1)
                                            .addComponent(blankAmountText1)
                                            .addComponent(blankAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(blankSearch)
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(stockTurnoverRepo)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(backupR)
                                            .addComponent(backupM)
                                            .addComponent(advisorEdit))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBlanksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBlanksButtonActionPerformed
        try {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyy");
            LocalDate localDate = LocalDate.now();
             //2016/11/16
            // TODO add your handling code here:
            for(int i=0;i<Integer.parseInt(blankAmount.getText());i++)
                db.statement("INSERT INTO `ats_sysdb`.`blank` (`idblank`, `type`, `date_received`) VALUES ('"+blankType.getSelectedItem()+String.format("%04d", MainGUI.stockno)+String.format("%04d", i)+"', '"+blankType.getSelectedItem()+"', '"+dtf.format(localDate)+"')");
            MainGUI.stockno++;
            db.statement("UPDATE `ats_sysdb`.`agencydetails` SET `lateststock`='"+MainGUI.stockno+"' WHERE `name`='ATS'");

        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_addBlanksButtonActionPerformed

    private void backupMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupMActionPerformed
        /*
        try {
            // TODO add your handling code here:

            Runtime.getRuntime().exec("cmd /c start backup.exe");
        } catch (IOException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
        
        try{     
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyyyhhmm");
            LocalDateTime localDate = LocalDateTime.now();
            
            
            CodeSource codeSource = RestoreBackupGUI.class.getProtectionDomain().getCodeSource();
            File jarFile = new File(codeSource.getLocation().toURI().getPath());
            String jarDir = jarFile.getParentFile().getPath();
            System.out.println(jarDir);
            Connection connection = db.getConnectionFromPool();
            String executeCmd = "";
            if(connection!=null){
                
                String d2 = new String(db.decoded, StandardCharsets.UTF_8);
                executeCmd = "cmd /c mysqldump --opt -h "+d2+" -P 3306 -u ATS -p220396 ats_sysdb > \""+jarDir+"\\backup\\ATS"+dtf.format(localDate)+".sql\"";   
                
                // executeCmd = PathToMySqlDumpFile+"mysqldump -h "+HOSTIP+" -P "+PORT+" -u "+USER+" -p"+PASS+" "+database+" -r "+path;
                
                
                
                Process runtimeProcess =Runtime.getRuntime().exec(executeCmd);
                int processComplete = runtimeProcess.waitFor();
                if(processComplete == 0){
                    System.out.println("Backup taken successfully");
                    jLabel2.setText("Backup taken successfully");
                    jLabel2.setForeground(Color.green);
                } else {
                    System.out.println("Could not take mysql backup");
                    jLabel2.setText("Could not take mysql backup");
                    jLabel2.setForeground(Color.red);
                }
            } else{
                System.out.println("connection not sucess");
            }
            
            db.returnConnectionToPool(connection);
        }catch (IOException | InterruptedException e) {
        }       catch (URISyntaxException ex) {
            Logger.getLogger(RestoreBackupGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        
        
        
        
    }//GEN-LAST:event_backupMActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        
        ATSFrontEnd.visi();
        
        
    }//GEN-LAST:event_logOutActionPerformed

    private void blankAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blankAmountActionPerformed

    private void assignBlanksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBlanksActionPerformed
        // TODO add your handling code here:
        String ty = (String) blankTypeAssign.getSelectedItem();
        int a = Integer.parseInt(blankAmountAssign.getText());
        int sel = userTable.getSelectedRow();
        int reqa=0;
        int l=0; long[] arr= new long[100];
        String user =(String) userTable.getModel().getValueAt(sel, 0);
        try {
            reqa = db.get1INT("SELECT reqblack FROM ats_sysdb.staff WHERE username = '"+user+"'")[0];
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int f = reqa-a; if(f<0)f=0;
        
        
        
        try {
            arr = db.get1LONG("SELECT idblank FROM ats_sysdb.blank WHERE `username`='0' AND `idblank` LIKE \""+ty+"%\"");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while(arr[l]!=0)
            l++;
        //System.out.println(ty);
        System.out.println(l);
        
        if(l>=a)
        {
        for(int i=0 ; i<a ; i++)
        {
            try {
                    db.statement("UPDATE `ats_sysdb`.`blank` SET `username`='"+user+"' WHERE `username`='0' AND `idblank` LIKE \""+arr[i]+"\"");
                } 
            catch (SQLException ex) {
                Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
        
            }
        try {
                db.statement("UPDATE `ats_sysdb`.`staff` SET `reqblack`='"+f+"' WHERE `username`='"+user+"'");
            } catch (SQLException ex) {
                Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_assignBlanksActionPerformed

    private void blankAmountAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankAmountAssignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blankAmountAssignActionPerformed

    private void searchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBoxFocusGained
        // TODO add your handling code here:
        this.searchBox.selectAll();
    }//GEN-LAST:event_searchBoxFocusGained

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        
        /////////////////////////////////
        
        try {
            String[] s,n; int[] r;
            if(!"".equals(searchBox.getText()) && !"Search".equals(searchBox.getText()))
            {
                s =db.get1String("SELECT username FROM ats_sysdb.staff WHERE type = 1 AND username LIKE '%"+searchBox.getText()+"%'");
                n =db.get1String("SELECT name FROM ats_sysdb.staff WHERE type = 1 AND username LIKE '%"+searchBox.getText()+"%'");
                r =db.get1INT("SELECT reqblack FROM ats_sysdb.staff WHERE type = 1 AND username LIKE '%"+searchBox.getText()+"%'");
            }
            else
            {
                s =db.get1String("SELECT username FROM ats_sysdb.staff WHERE type = 1");
                n =db.get1String("SELECT name FROM ats_sysdb.staff WHERE type = 1");
                r =db.get1INT("SELECT reqblack FROM ats_sysdb.staff WHERE type = 1");
            }
            int i=0;
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            int rowCount = model.getRowCount();

            for (int x = rowCount - 1; x >= 0; x--) 
                model.removeRow(i);
        
            while(s[i]!=null)
            {
                model.addRow(new Object[]{s[i], n[i], r[i]});
                //userTable.getModel().setValueAt(s[i],i,0);
                //userTable.getModel().setValueAt(n[i],i,1);
                //userTable.getModel().setValueAt(r[i],i,2);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        
    }//GEN-LAST:event_findActionPerformed

    private void backupRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupRActionPerformed
        restoreBackupGUI1.setVisible(true);
        
          
    }//GEN-LAST:event_backupRActionPerformed

    private void advisorEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advisorEditActionPerformed
        // TODO add your handling code here:
        maintainAdvisorsGUI1.setVisible(true);
        
        
    }//GEN-LAST:event_advisorEditActionPerformed

    private void blankAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blankAmountFocusGained
        // TODO add your handling code here:
        this.blankAmount.selectAll();
        //blankAmount.setText(Integer.toString(JFrame.MAXIMIZED_BOTH));
    }//GEN-LAST:event_blankAmountFocusGained

    private void addBlanksButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBlanksButton1ActionPerformed
        try {
            // TODO add your handling code here:
            //db.statement("DELETE FROM `ats_sysdb`.`blank` WHERE `idblank` LIKE '___"+String.format("%04d", Integer.parseInt(blankAmount1.getText()))+"____'");
            db.statement("UPDATE `ats_sysdb`.`blank` SET `void`='1' WHERE `idblank` LIKE '___"+String.format("%04d", Integer.parseInt(blankAmount1.getText()))+"____'");
            //int nr =db.get1INT("SELECT lateststock FROM ats_sysdb.agencydetails WHERE `name`='ATS'")[0]-1;
            //db.statement("UPDATE `ats_sysdb`.`agencydetails` SET `lateststock`='"+nr+"' WHERE `name`='ATS'");
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_addBlanksButton1ActionPerformed

    private void blankAmount1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blankAmount1FocusGained
        // TODO add your handling code here:
        
        this.blankAmount1.selectAll();
        
    }//GEN-LAST:event_blankAmount1FocusGained

    private void blankAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankAmount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blankAmount1ActionPerformed

    private void editAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAgencyActionPerformed
        // TODO add your handling code here:
        agencyDetailsGUI1.setVisible(true);
    }//GEN-LAST:event_editAgencyActionPerformed

    private void stockTurnoverRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTurnoverRepoActionPerformed
        // TODO add your handling code here:
        
        ATSReportView r = new ATSReportView(0);
        r.setVisible(true);
        
        
    }//GEN-LAST:event_stockTurnoverRepoActionPerformed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jLabel1MouseMoved

    private void blankSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankSearchActionPerformed
        // TODO add your handling code here:
        
        ManageBlanks r = new ManageBlanks();
        r.setVisible(true);
        
    }//GEN-LAST:event_blankSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBlanksButton;
    private javax.swing.JButton addBlanksButton1;
    private javax.swing.JButton advisorEdit;
    private ats.frontend.AdminStuff.AgencyDetailsGUI agencyDetailsGUI1;
    private javax.swing.JButton assignBlanks;
    private javax.swing.JButton backupM;
    private javax.swing.JButton backupR;
    private javax.swing.JTextField blankAmount;
    private javax.swing.JTextField blankAmount1;
    private javax.swing.JTextField blankAmountAssign;
    private javax.swing.JLabel blankAmountText;
    private javax.swing.JLabel blankAmountText1;
    private javax.swing.JLabel blankAmountTextAssign;
    private javax.swing.JButton blankSearch;
    private javax.swing.JComboBox<String> blankType;
    private javax.swing.JComboBox<String> blankTypeAssign;
    private javax.swing.JLabel blankTypeText;
    private javax.swing.JButton editAgency;
    private javax.swing.JButton find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOut;
    private ats.frontend.AdminStuff.MaintainAdvisorsGUI maintainAdvisorsGUI1;
    private ats.frontend.AdminStuff.RestoreBackupGUI restoreBackupGUI1;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton stockTurnoverRepo;
    private javax.swing.JLabel typeText;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
