/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ats.frontend.AdminStuff;

import ats.frontend.DBInter;
import ats.frontend.Login;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author armor
 */
public class MaintainAdvisorsGUI extends javax.swing.JPanel {

    /**
     * Creates new form MaintainAdvisorsGUI
     */
    
    DBInter db = Login.db;
    public MaintainAdvisorsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        searchBox = new javax.swing.JTextField();
        find = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        mail = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        adress = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        userType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(904, 543));

        jFrame1.setBackground(new java.awt.Color(0, 0, 0));
        jFrame1.setOpaque(false);

        cancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "UserName", "Password", "Name", "Adress", "Phone", "E-Mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        searchBox.setText("Search");
        searchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBoxFocusGained(evt);
            }
        });
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        find.setText("Find");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addButton.setText("Add User");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        mail.setText("E-Mail");
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
        });

        phone.setText("Phone Nr.");
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
        });

        adress.setText("Adress");
        adress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adressFocusGained(evt);
            }
        });

        name.setText("Name");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Maintain Users");

        deleteButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteButton.setText("Delete Selected");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deleteButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteButton1.setText("Edit Selected");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        user.setText("UserName");
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        password.setText("jPasswordField1");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });

        userType.setText("Type");
        userType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTypeFocusGained(evt);
            }
        });
        userType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("0=Admin 1=Adisor 2=Of.Manager");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1);
        jFrame1.setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mail)
                    .addComponent(phone)
                    .addComponent(adress)
                    .addComponent(name)
                    .addComponent(user)
                    .addComponent(password)
                    .addComponent(userType)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton1)
                        .addGap(308, 308, 308)
                        .addComponent(cancel))
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                            .addComponent(searchBox)
                            .addGap(18, 18, 18)
                            .addComponent(find))))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(find)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(deleteButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void searchBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBoxFocusGained
        // TODO add your handling code here:
        this.searchBox.selectAll();
    }//GEN-LAST:event_searchBoxFocusGained

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        
        try {
            String[] uname,lname,address,email,pass,uphone;  int[] id,typ;
            if(!"".equals(searchBox.getText()) && !"Search".equals(searchBox.getText()))
            {
                id = db.get1INT("SELECT idstaff FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                typ= db.get1INT("SELECT type FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                uname= db.get1String("SELECT username FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                pass=db.get1String("SELECT password FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                lname=db.get1String("SELECT name FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                address=db.get1String("SELECT address FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                uphone=db.get1String("SELECT phone FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                email=db.get1String("SELECT email FROM ats_sysdb.staff WHERE lastname LIKE '%"+searchBox.getText()+"%'");
                        
                        
            }
            else
            {
                
                id = db.get1INT("SELECT idstaff FROM ats_sysdb.staff");
                typ= db.get1INT("SELECT type FROM ats_sysdb.staff");
                uname= db.get1String("SELECT username FROM ats_sysdb.staff");
                pass=db.get1String("SELECT password FROM ats_sysdb.staff");
                lname=db.get1String("SELECT name FROM ats_sysdb.staff");
                address=db.get1String("SELECT address FROM ats_sysdb.staff");
                uphone=db.get1String("SELECT phone FROM ats_sysdb.staff");
                email=db.get1String("SELECT email FROM ats_sysdb.staff");
                
                
            }
            int i=0;
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            int rowCount = model.getRowCount();

            for (int x = rowCount - 1; x >= 0; x--) 
                model.removeRow(i);
        
            while(id[i]!=0)
            {
                model.addRow(new Object[]{id[i] , typ[i] , uname[i] , pass[i] , lname[i] , address[i] , uphone[i] , email[i] });
                //userTable.getModel().setValueAt(s[i],i,0);
                //userTable.getModel().setValueAt(n[i],i,1);
                //userTable.getModel().setValueAt(r[i],i,2);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        
        
        
    }//GEN-LAST:event_findActionPerformed

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        // TODO add your handling code here:
        this.mail.selectAll();
    }//GEN-LAST:event_mailFocusGained

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
        this.phone.selectAll();
    }//GEN-LAST:event_phoneFocusGained

    private void adressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adressFocusGained
        // TODO add your handling code here:
        this.adress.selectAll();
    }//GEN-LAST:event_adressFocusGained

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        this.name.selectAll();
    }//GEN-LAST:event_nameFocusGained

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        // TODO add your handling code here:
        this.user.selectAll();
        
    }//GEN-LAST:event_userFocusGained

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        
        this.password.selectAll();
    }//GEN-LAST:event_passwordFocusGained

    private void userTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTypeFocusGained
        // TODO add your handling code here:
        this.userType.selectAll();
    }//GEN-LAST:event_userTypeFocusGained

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTypeActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String ty,un,pwd,n,ad,pnr,eml;
        ty=userType.getText();
        un=user.getText();
        pwd=password.getText();
        n=name.getText();
        ad=adress.getText();
        pnr=phone.getText();
        eml=mail.getText();
        try {
            db.statement("INSERT INTO `ats_sysdb`.`staff` (`name`, `address`, `phone`, `email`, `username`, `password`, `type`) VALUES ('"+n+"', '"+ad+"', '"+pnr+"', '"+eml+"', '"+un+"', '"+pwd+"', '"+ty+"')");
        } catch (SQLException ex) {
            Logger.getLogger(MaintainAdvisorsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            // TODO add your handling code here:
            
            int fn=(int)userTable.getModel().getValueAt(userTable.getSelectedRow(), 0);
            db.statement("DELETE FROM `ats_sysdb`.`staff` WHERE `idstaff` LIKE '"+fn+"'");
        } catch (SQLException ex) {
            Logger.getLogger(MaintainAdvisorsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        try {
            // TODO add your handling code here:
            String namee,add,phon,eml,dob,pp,un,pwd;  int typ; float iid;
            
            iid=(float)userTable.getModel().getValueAt(userTable.getSelectedRow(), 0);
            typ=(int)userTable.getModel().getValueAt(userTable.getSelectedRow(), 1);
            un=(String)userTable.getModel().getValueAt(userTable.getSelectedRow(), 2);
            pwd=(String)userTable.getModel().getValueAt(userTable.getSelectedRow(), 3);
            namee=(String)userTable.getModel().getValueAt(userTable.getSelectedRow(), 4);
            add=(String)userTable.getModel().getValueAt(userTable.getSelectedRow(), 5);
            phon=(String)userTable.getModel().getValueAt(userTable.getSelectedRow(), 6);
            eml=(String)userTable.getModel().getValueAt(userTable.getSelectedRow(), 7);
            
            
            

            db.statement("UPDATE `ats_sysdb`.`staff` SET `name`='"+namee+"', `address`='"+add+"', `phone`='"+phon+"', `email`='"+eml+"', `username`='"+un+"', `password`='"+pwd+"', `type`='"+typ+"' WHERE `idstaff`='"+iid+"';");
        } catch (SQLException ex) {
            Logger.getLogger(MaintainAdvisorsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_deleteButton1ActionPerformed


   
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField adress;
    private javax.swing.JButton cancel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JButton find;
    private javax.swing.JPanel jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField searchBox;
    private javax.swing.JTextField user;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField userType;
    // End of variables declaration//GEN-END:variables
}
