/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ats.frontend.AdvisorStuff;

import ats.frontend.ATSFrontEnd;
import ats.frontend.ATSReportView;
import ats.frontend.MainGUI;

/**
 *
 * @author armor
 */
public class AdvisorGUI extends javax.swing.JPanel {

    /**
     * Creates new form AdminGUI
     */
    public AdvisorGUI() {
        initComponents();
        jLabel1.setText("Welcome "+MainGUI.userName);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        requestBlank = new javax.swing.JButton();
        createIReport = new javax.swing.JButton();
        manageCustomers = new javax.swing.JButton();
        transaction = new javax.swing.JButton();
        type = new javax.swing.JComboBox<>();
        typeText = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        amountText = new javax.swing.JLabel();
        createIReport1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(904, 543));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<Advisor's name here>>");

        logOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        requestBlank.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        requestBlank.setText("Request Blanks");

        createIReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        createIReport.setText("Create Individual Report Domestic");
        createIReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createIReportActionPerformed(evt);
            }
        });

        manageCustomers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        manageCustomers.setText("Manage Customers");
        manageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersActionPerformed(evt);
            }
        });

        transaction.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        transaction.setText("Ticket Transaction");
        transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionActionPerformed(evt);
            }
        });

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "444", "440", "420", "201", "101", "451", "452" }));

        typeText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeText.setForeground(new java.awt.Color(255, 255, 255));
        typeText.setText("Type");

        amount.setBackground(new java.awt.Color(0, 0, 0));
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setText("0");
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        amountText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountText.setForeground(new java.awt.Color(255, 255, 255));
        amountText.setText("Amount");

        createIReport1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        createIReport1.setText("Create Individual Report Interline");
        createIReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createIReport1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(requestBlank)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(amount)
                                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeText)
                                    .addComponent(amountText, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manageCustomers))))
                        .addGap(0, 364, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createIReport)
                        .addGap(18, 18, 18)
                        .addComponent(createIReport1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(manageCustomers)
                        .addGap(18, 18, 18)
                        .addComponent(transaction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                        .addComponent(logOut))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(requestBlank))
                            .addComponent(typeText))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountText)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createIReport)
                            .addComponent(createIReport1))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        ATSFrontEnd.visi();
    }//GEN-LAST:event_logOutActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionActionPerformed

        
        TransactionGUI r = new TransactionGUI();
        r.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_transactionActionPerformed

    private void manageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersActionPerformed
        // TODO add your handling code here:
        ManageCustomersGUI r = new ManageCustomersGUI(false);
        r.setVisible(true);
        
    }//GEN-LAST:event_manageCustomersActionPerformed

    private void createIReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createIReportActionPerformed
        // TODO add your handling code here:
        
        ATSReportView r = new ATSReportView(1);
        r.setVisible(true);
    }//GEN-LAST:event_createIReportActionPerformed

    private void createIReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createIReport1ActionPerformed
        // TODO add your handling code here:
        
        ATSReportView r = new ATSReportView(2);
        r.setVisible(true);
    }//GEN-LAST:event_createIReport1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel amountText;
    private javax.swing.JButton createIReport;
    private javax.swing.JButton createIReport1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton manageCustomers;
    private javax.swing.JButton requestBlank;
    private javax.swing.JButton transaction;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JLabel typeText;
    // End of variables declaration//GEN-END:variables
}
