/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ats.frontend.AdvisorStuff;

/**
 *
 * @author armor
 */
public class Card extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */
    public Card() {
        initComponents();
    }
    
    
    public String[] details()
    {
        String[] x = new String[3];
        x[0]=flight.getText();
        x[1]=flight1.getText();
        x[2]=flight2.getText();
        
        return x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightLabel = new javax.swing.JLabel();
        flightLabel1 = new javax.swing.JLabel();
        flightLabel2 = new javax.swing.JLabel();
        flight = new javax.swing.JTextField();
        flight1 = new javax.swing.JTextField();
        flight2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));

        flightLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        flightLabel.setForeground(new java.awt.Color(255, 255, 255));
        flightLabel.setText("Card No.");

        flightLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        flightLabel1.setForeground(new java.awt.Color(255, 255, 255));
        flightLabel1.setText("CVC");

        flightLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        flightLabel2.setForeground(new java.awt.Color(255, 255, 255));
        flightLabel2.setText("Expiry");

        flight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                flightFocusGained(evt);
            }
        });
        flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightActionPerformed(evt);
            }
        });

        flight1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                flight1FocusGained(evt);
            }
        });
        flight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flight1ActionPerformed(evt);
            }
        });

        flight2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                flight2FocusGained(evt);
            }
        });
        flight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flight2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightLabel2)
                            .addComponent(flightLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flight2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(flight1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(flightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(flight)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void flightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_flightFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_flightFocusGained

    private void flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightActionPerformed

    private void flight1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_flight1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_flight1FocusGained

    private void flight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flight1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flight1ActionPerformed

    private void flight2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_flight2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_flight2FocusGained

    private void flight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flight2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flight2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField flight;
    private javax.swing.JTextField flight1;
    private javax.swing.JTextField flight2;
    private javax.swing.JLabel flightLabel;
    private javax.swing.JLabel flightLabel1;
    private javax.swing.JLabel flightLabel2;
    // End of variables declaration//GEN-END:variables
}
