/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ats.frontend.AdvisorStuff;

import ats.frontend.DBInter;
import ats.frontend.Login;
import ats.frontend.MainGUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author armor
 */
public class TransactionGUI extends javax.swing.JFrame {

    /**
     * Creates new form TransactionGUI
     */
    
    DBInter db = Login.db;
    
    
    public TransactionGUI() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        card2.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saleType = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        paymentType = new javax.swing.JComboBox<>();
        paymentLabel = new javax.swing.JLabel();
        flightType = new javax.swing.JComboBox<>();
        flightTypeLabel = new javax.swing.JLabel();
        currencyType = new javax.swing.JComboBox<>();
        currencyLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        flight = new javax.swing.JTextField();
        flightLabel = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        seatLabel = new javax.swing.JLabel();
        seat = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        manageCustomer = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        totalLabel1 = new javax.swing.JLabel();
        total1 = new javax.swing.JTextField();
        customerLabel1 = new javax.swing.JLabel();
        customerName1 = new javax.swing.JTextField();
        card2 = new ats.frontend.AdvisorStuff.Card();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        typeLabel1 = new javax.swing.JLabel();
        blankType = new javax.swing.JComboBox<>();
        customerName2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        exchangeL = new javax.swing.JLabel();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Payment Type");

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Manage Customers");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(759, 582));

        cancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaction Menu");

        saleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sale", "Refund" }));
        saleType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                saleTypeItemStateChanged(evt);
            }
        });
        saleType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleTypeActionPerformed(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Type");

        paymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card" }));
        paymentType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paymentTypeItemStateChanged(evt);
            }
        });
        paymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTypeActionPerformed(evt);
            }
        });

        paymentLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymentLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentLabel.setText("Payment Type");

        flightType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domestic", "International" }));
        flightType.setEnabled(false);

        flightTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        flightTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        flightTypeLabel.setText("Flight Type");

        currencyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "USD" }));
        currencyType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                currencyTypeItemStateChanged(evt);
            }
        });

        currencyLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        currencyLabel.setForeground(new java.awt.Color(255, 255, 255));
        currencyLabel.setText("Currency");

        customerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setText("Customer");

        customerName.setText("FirstName");
        customerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerNameFocusGained(evt);
            }
        });
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });

        flight.setText("Name");
        flight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                flightFocusGained(evt);
            }
        });
        flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightActionPerformed(evt);
            }
        });

        flightLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        flightLabel.setForeground(new java.awt.Color(255, 255, 255));
        flightLabel.setText("Flight");

        total.setEditable(false);
        total.setText(price.getText());
        total.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                totalMouseMoved(evt);
            }
        });
        total.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalFocusGained(evt);
            }
        });
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalLabel.setText("Grand Total");

        seatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seatLabel.setForeground(new java.awt.Color(255, 255, 255));
        seatLabel.setText("Seat");

        seat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                seatFocusGained(evt);
            }
        });
        seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Price");

        price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                priceFocusLost(evt);
            }
        });
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        manageCustomer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        manageCustomer.setText("Manage Customers");
        manageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerActionPerformed(evt);
            }
        });

        paymentButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        paymentButton.setText("Confirm");
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        totalLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalLabel1.setForeground(new java.awt.Color(255, 255, 255));
        totalLabel1.setText("Paid");

        total1.setText(price.getText());
        total1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total1FocusGained(evt);
            }
        });
        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });

        customerLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel1.setText("Transaction ID");

        customerName1.setEnabled(false);
        customerName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerName1FocusGained(evt);
            }
        });
        customerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerName1ActionPerformed(evt);
            }
        });

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Extra Luggage");

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Misc");

        typeLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel1.setText("Type");

        blankType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "201", "101", "444", "440", "420" }));
        blankType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blankTypeItemStateChanged(evt);
            }
        });

        customerName2.setText("LastName");
        customerName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerName2FocusGained(evt);
            }
        });
        customerName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerName2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("                 ");

        exchangeL.setForeground(new java.awt.Color(204, 204, 204));
        exchangeL.setText("            ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paymentButton)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancel))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(customerLabel)
                                            .addGap(31, 31, 31))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(paymentLabel)))
                                    .addComponent(currencyLabel)
                                    .addComponent(flightLabel)
                                    .addComponent(customerLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(currencyType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saleType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total)
                                    .addComponent(flight)
                                    .addComponent(totalLabel)
                                    .addComponent(customerName1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customerName2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(totalLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox2)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(typeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(flightTypeLabel)
                                                    .addComponent(priceLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(blankType, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jCheckBox1)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(flightType, javax.swing.GroupLayout.Alignment.LEADING, 0, 115, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(seatLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(manageCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(card2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exchangeL, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeLabel1)
                    .addComponent(blankType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currencyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageCustomer)
                    .addComponent(customerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customerName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exchangeL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentButton)
                    .addComponent(cancel)
                    .addComponent(jLabel2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void customerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFocusGained
        // TODO add your handling code here:
        this.customerName.selectAll();
    }//GEN-LAST:event_customerNameFocusGained

    private void saleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleTypeActionPerformed

    private void flightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_flightFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_flightFocusGained

    private void flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightActionPerformed

    private void totalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFocusGained

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void seatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seatFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_seatFocusGained

    private void seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatActionPerformed

    private void priceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFocusGained

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void priceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusLost
        
    }//GEN-LAST:event_priceFocusLost

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        try {
            // TODO add your handling code here:
            long[] id = db.get1LONG("SELECT idblank FROM ats_sysdb.blank WHERE idblank LIKE '"+(String)blankType.getSelectedItem()+"%' AND void=0 AND username = '"+MainGUI.userName+"'");
            System.out.println((String)blankType.getSelectedItem());
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyy");
            LocalDate localDate = LocalDate.now();
            String[] cust = db.get1String("SELECT passportno FROM ats_sysdb.customer WHERE firstname LIKE '"+customerName.getText()+"' AND lastname LIKE '"+customerName2.getText()+"'");
            String[] cType = db.get1String("SELECT type FROM ats_sysdb.customer WHERE firstname LIKE '"+customerName.getText()+"' AND lastname LIKE '"+customerName2.getText()+"'");
            
            if("Sale".equals((String)saleType.getSelectedItem()))
            {
                float c =db.get1FLOAT("SELECT commission FROM ats_sysdb.agencydetails")[0];
                db.statement("INSERT INTO `ats_sysdb`.`transaction` (`idtransaction`, `date`, `type`, `method`, `amount`, `idcustomer`, `idstaff`, `idblank_misc`, `idblank_luggage`, `interline`, `currency`, `idcard`, `commission`) VALUES ('"+id[0]+"', '"+dtf.format(localDate)+"', 'sale', '"+(String)paymentType.getSelectedItem()+"', '"+(String)total.getText()+"', '"+cust[0]+"', '"+MainGUI.userName+"', '0', '0', '"+flightType.getSelectedIndex()+"', '"+currencyType.getSelectedIndex()+"', '0', '"+c+"');");
                db.statement("UPDATE `ats_sysdb`.`blank` SET `void`='1' WHERE `idblank`='"+id[0]+"'");
                db.statement("UPDATE `ats_sysdb`.`blank` SET `date_sold`='"+dtf.format(localDate)+"' WHERE `idblank`='"+id[0]+"'");
                db.statement("UPDATE `ats_sysdb`.`blank` SET `username`='"+MainGUI.userName+"' WHERE `idblank`='"+id[0]+"'");
                
                if(jCheckBox1.isSelected())
                {
                    long[] luggage = db.get1LONG("SELECT idblank FROM ats_sysdb.blank WHERE idblank LIKE '451%' AND void=0 AND username = '"+MainGUI.userName+"'");
                    db.statement("UPDATE `ats_sysdb`.`transaction` SET `idblank_luggage`='"+luggage[0]+"' WHERE `idtransaction`='"+id[0]+"'");
                    db.statement("UPDATE `ats_sysdb`.`blank` SET `void`='1' WHERE `idblank`='"+luggage[0]+"'");
                    db.statement("UPDATE `ats_sysdb`.`blank` SET `username`='"+MainGUI.userName+"' WHERE `idblank`='"+luggage[0]+"'");
                }
                if(jCheckBox2.isSelected())
                {
                    long[] mco = db.get1LONG("SELECT idblank FROM ats_sysdb.blank WHERE idblank LIKE '452%' AND void=0 AND username = '"+MainGUI.userName+"'");
                    db.statement("UPDATE `ats_sysdb`.`transaction` SET `idblank_misc`='"+mco[0]+"' WHERE `idtransaction`='"+id[0]+"'");
                    db.statement("UPDATE `ats_sysdb`.`blank` SET `void`='1' WHERE `idblank`='"+mco[0]+"'");
                    db.statement("UPDATE `ats_sysdb`.`blank` SET `username`='"+MainGUI.userName+"' WHERE `idblank`='"+mco[0]+"'");
                    
                }
                
                if("Card".equals((String)paymentType.getSelectedItem()))
                {
                    long[] card = db.get1LONG("SELECT idcard FROM ats_sysdb.card WHERE cardno LIKE '"+card2.details()[0]+"' AND CVC LIKE '"+card2.details()[1]+"' AND expiry LIKE '"+card2.details()[2]+"'");
                    db.statement("UPDATE `ats_sysdb`.`transaction` SET `idcard`='"+card[0]+"' WHERE `idtransaction`='"+id[0]+"'");
                    
                    db.statement("UPDATE `ats_sysdb`.`transaction` SET `paid`='"+price.getText()+"' WHERE `idtransaction`='"+id[0]+"'");
                    //db.statement("UPDATE `ats_sysdb`.`blank` SET `void`='1' WHERE `idblank`='"+mco[0]+"'");
                    
                }else db.statement("UPDATE `ats_sysdb`.`transaction` SET `paid`='"+total1.getText()+"' WHERE `idtransaction`='"+id[0]+"'");
                
                
                if(currencyType.getSelectedIndex()==1)
                {
                    float r =db.get1FLOAT("SELECT exchange_rate FROM ats_sysdb.agencydetails")[0];
                    db.statement("UPDATE `ats_sysdb`.`transaction` SET `exchange_rate`='"+r+"' WHERE `idtransaction`='"+id[0]+"'");
                    
                    
                    
                }
                
                
                
                
            }else
            {
                db.statement("UPDATE `ats_sysdb`.`transaction` SET `amount`='0' WHERE `idtransaction`='"+customerName1.getText()+"'");
                
            }
            jLabel2.setText("Transaction Successful"); jLabel2.setForeground(Color.getHSBColor(115,77,75));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(TransactionGUI.class.getName()).log(Level.SEVERE, null, ex);
            jLabel2.setText("Transaction Failed"); jLabel2.setForeground(Color.red);
        }
        
        
        
        
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void paymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTypeActionPerformed

    private void total1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_total1FocusGained

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total1ActionPerformed

    private void paymentTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paymentTypeItemStateChanged
        // TODO add your handling code here:
        if(paymentType.getSelectedIndex()==0)
        {
            total1.setEditable(true);
            total1.setBackground(Color.white);
            card2.setVisible(false);
        }
        else 
        {
            total1.setEditable(false);
            total1.setBackground(Color.black);
            card2.setVisible(true);
        }
    }//GEN-LAST:event_paymentTypeItemStateChanged

    private void customerName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_customerName1FocusGained

    private void customerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerName1ActionPerformed

    private void saleTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_saleTypeItemStateChanged
        // TODO add your handling code here:
        if(saleType.getSelectedIndex()==1)
        {
            customerName1.setEnabled(true);
            //total1.setBackground(Color.white);
            flight.setEnabled(false);
            flightType.setEnabled(false);
            seat.setEnabled(false);
            currencyType.setEnabled(false);
            price.setEnabled(false);
            customerName.setEnabled(false);
            customerName2.setEnabled(false);
            paymentType.setEnabled(false);
            blankType.setEnabled(false);
            total1.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jCheckBox2.setEnabled(false);
        }
        else 
        {
            customerName1.setEnabled(false);
            //total1.setBackground(Color.black);
            flight.setEnabled(true);
            flightType.setEnabled(true);
            seat.setEnabled(true);
            currencyType.setEnabled(true);
            price.setEnabled(true);
            customerName.setEnabled(true);
            customerName2.setEnabled(true);
            paymentType.setEnabled(true);
            blankType.setEnabled(true);
            total1.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox2.setEnabled(true);
        }
        
    }//GEN-LAST:event_saleTypeItemStateChanged

    private void manageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerActionPerformed
        // TODO add your handling code here:
        
        ManageCustomersGUI r = new ManageCustomersGUI(false);
        r.setVisible(true);
        
    }//GEN-LAST:event_manageCustomerActionPerformed

    private void customerName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerName2FocusGained
        // TODO add your handling code here:
        this.customerName2.selectAll();
    }//GEN-LAST:event_customerName2FocusGained

    private void customerName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerName2ActionPerformed

    private void blankTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blankTypeItemStateChanged
        // TODO add your handling code here:
        if(blankType.getSelectedIndex()<2)
            flightType.setSelectedIndex(0);
        if(blankType.getSelectedIndex()>=2)
            flightType.setSelectedIndex(1);
        
    }//GEN-LAST:event_blankTypeItemStateChanged

    private void currencyTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_currencyTypeItemStateChanged
        try {
            // TODO add your handling code here:

            if(currencyType.getSelectedIndex()==1)
                {
                    float r =db.get1FLOAT("SELECT exchange_rate FROM ats_sysdb.agencydetails")[0];
                    String c =db.get1String("SELECT local_currency FROM ats_sysdb.agencydetails")[0];
                    exchangeL.setText("Exchange rate from "+c+" to USD is "+r+" And USD to "+c+" is "+1/r);
                }
            else exchangeL.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(TransactionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_currencyTypeItemStateChanged

    private void totalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseMoved
        // TODO add your handling code here:
        try {
            
            
            float c =db.get1FLOAT("SELECT commission FROM ats_sysdb.agencydetails")[0];
            float r =db.get1FLOAT("SELECT exchange_rate FROM ats_sysdb.agencydetails")[0];
            float d =db.get1FLOAT("SELECT discount FROM ats_sysdb.customer WHERE firstname LIKE '"+customerName.getText()+"' AND lastname LIKE '"+customerName2.getText()+"'")[0];
            float amountto = Integer.parseInt(price.getText());
            float grand;
            if(currencyType.getSelectedIndex()==0)
                grand = (amountto - amountto*d/100)+(amountto - amountto*d/100)*c/100;
            else
                grand = ((amountto - amountto*d/100)+(amountto - amountto*d/100)*c/100)*r;
            
            this.total.setText(Float.toString(grand));
        } catch (SQLException ex) {
            Logger.getLogger(TransactionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_totalMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blankType;
    private javax.swing.JButton cancel;
    private ats.frontend.AdvisorStuff.Card card2;
    private javax.swing.JLabel currencyLabel;
    private javax.swing.JComboBox<String> currencyType;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerLabel1;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField customerName1;
    private javax.swing.JTextField customerName2;
    private javax.swing.JLabel exchangeL;
    private javax.swing.JTextField flight;
    private javax.swing.JLabel flightLabel;
    private javax.swing.JComboBox<String> flightType;
    private javax.swing.JLabel flightTypeLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageCustomer;
    private javax.swing.JButton paymentButton;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JComboBox<String> paymentType;
    private javax.swing.JTextField price;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JComboBox<String> saleType;
    private javax.swing.JTextField seat;
    private javax.swing.JLabel seatLabel;
    private javax.swing.JTextField total;
    private javax.swing.JTextField total1;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeLabel1;
    // End of variables declaration//GEN-END:variables
}
