/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ats.frontend.OfficeStuff;

import ats.frontend.ATSFrontEnd;
import ats.frontend.ATSReportView;
import ats.frontend.AdminStuff.AdminGUI;
import ats.frontend.AdvisorStuff.ManageCustomersGUI;
import ats.frontend.DBInter;
import ats.frontend.Login;
import ats.frontend.MainGUI;
import ats.frontend.ManageBlanks;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author armor
 */
public class OfficeGUI extends javax.swing.JPanel {

    /**
     * Creates new form AdminGUI
     * 
     *
     */
    
    
    DBInter db = Login.db;
    
    public OfficeGUI() {
        initComponents();
        jScrollPane1.setOpaque(false);
        jLabel1.setText("Welcome "+MainGUI.userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        setCommision = new javax.swing.JButton();
        returnBlanks = new javax.swing.JButton();
        stockReport = new javax.swing.JButton();
        domReport = new javax.swing.JButton();
        interReport = new javax.swing.JButton();
        discountRepo = new javax.swing.JButton();
        commisionProcent = new javax.swing.JTextField();
        procentLabel = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        genAlert = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        amount2 = new javax.swing.JTextField();
        amountLabel1 = new javax.swing.JLabel();
        returnBlanks2 = new javax.swing.JButton();
        typeLabel1 = new javax.swing.JLabel();
        amountLabel2 = new javax.swing.JLabel();
        returnBlanks3 = new javax.swing.JButton();
        amount3 = new javax.swing.JTextField();
        amountLabel4 = new javax.swing.JLabel();
        manageCustomers = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        blankSearch = new javax.swing.JButton();
        clientReport = new javax.swing.JButton();
        clientName = new javax.swing.JTextField();

        jButton7.setText("Log Out");

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(904, 543));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<Office Manager's name here>>");

        logOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        setCommision.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setCommision.setText("Set Commission");
        setCommision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCommisionActionPerformed(evt);
            }
        });

        returnBlanks.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        returnBlanks.setText("Return Blanks");
        returnBlanks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBlanksActionPerformed(evt);
            }
        });

        stockReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stockReport.setText("Stock Turnover Report");
        stockReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockReportActionPerformed(evt);
            }
        });

        domReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        domReport.setText("Domestic Sales Report");
        domReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domReportActionPerformed(evt);
            }
        });

        interReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        interReport.setText("Interline Sales Report");
        interReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interReportActionPerformed(evt);
            }
        });

        discountRepo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        discountRepo.setText("USD Rate Report");
        discountRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountRepoActionPerformed(evt);
            }
        });

        commisionProcent.setBackground(new java.awt.Color(0, 0, 0));
        commisionProcent.setForeground(new java.awt.Color(255, 255, 255));
        commisionProcent.setText("0.0000");
        commisionProcent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                commisionProcentFocusGained(evt);
            }
        });
        commisionProcent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commisionProcentActionPerformed(evt);
            }
        });

        procentLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        procentLabel.setForeground(new java.awt.Color(255, 255, 255));
        procentLabel.setText("%");

        amount.setBackground(new java.awt.Color(0, 0, 0));
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setText("0");
        amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountFocusGained(evt);
            }
        });
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        amountLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(255, 255, 255));
        amountLabel.setText("Batch");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Client Name", "Late Payment Due", "Amount Due"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        genAlert.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        genAlert.setText("Generate Alert For Selected");
        genAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genAlertActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Late Payment Alerts");

        amount2.setBackground(new java.awt.Color(0, 0, 0));
        amount2.setForeground(new java.awt.Color(255, 255, 255));
        amount2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amount2FocusGained(evt);
            }
        });
        amount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount2ActionPerformed(evt);
            }
        });

        amountLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountLabel1.setForeground(new java.awt.Color(255, 255, 255));
        amountLabel1.setText("Local Currency");

        returnBlanks2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        returnBlanks2.setText("Set");
        returnBlanks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBlanks2ActionPerformed(evt);
            }
        });

        typeLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel1.setText(amount3.getText());

        amountLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountLabel2.setForeground(new java.awt.Color(255, 255, 255));
        amountLabel2.setText("Conversion Rate to USD");

        returnBlanks3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        returnBlanks3.setText("Set");
        returnBlanks3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBlanks3ActionPerformed(evt);
            }
        });

        amount3.setBackground(new java.awt.Color(0, 0, 0));
        amount3.setForeground(new java.awt.Color(255, 255, 255));
        amount3.setText("0");
        amount3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amount3FocusGained(evt);
            }
        });
        amount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount3ActionPerformed(evt);
            }
        });

        amountLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountLabel4.setForeground(new java.awt.Color(255, 255, 255));
        amountLabel4.setText(amount2.getText());

        manageCustomers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        manageCustomers.setText("Manage Customers");
        manageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        blankSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        blankSearch.setText("Blank Search");
        blankSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankSearchActionPerformed(evt);
            }
        });

        clientReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clientReport.setText("Client Report");
        clientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientReportActionPerformed(evt);
            }
        });

        clientName.setBackground(new java.awt.Color(0, 0, 0));
        clientName.setForeground(new java.awt.Color(255, 255, 255));
        clientName.setText("Client Name");
        clientName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientNameFocusGained(evt);
            }
        });
        clientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stockReport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(domReport))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(amountLabel1)
                                            .addComponent(amountLabel2))
                                        .addGap(4, 4, 4)
                                        .addComponent(amount3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(returnBlanks3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amountLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(typeLabel1))
                                    .addComponent(manageCustomers)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(setCommision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(returnBlanks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(amount)
                                            .addComponent(commisionProcent, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(procentLabel)
                                            .addComponent(amountLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(amount2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(returnBlanks2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(blankSearch))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(genAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(interReport)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(discountRepo)
                                        .addGap(18, 18, 18)
                                        .addComponent(logOut))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clientReport)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(commisionProcent)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(setCommision)
                                .addComponent(procentLabel)))
                        .addGap(57, 57, 57)
                        .addComponent(blankSearch)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnBlanks)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageCustomers)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountLabel1)
                            .addComponent(amount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnBlanks2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountLabel2)
                            .addComponent(typeLabel1)
                            .addComponent(returnBlanks3)
                            .addComponent(amount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountLabel4))
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genAlert)
                            .addComponent(refreshButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientReport)
                            .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockReport)
                    .addComponent(domReport)
                    .addComponent(interReport)
                    .addComponent(discountRepo)
                    .addComponent(logOut))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void commisionProcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commisionProcentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commisionProcentActionPerformed

    private void commisionProcentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_commisionProcentFocusGained
        try {
            // TODO add your handling code here:
            
            commisionProcent.setText(Float.toString(db.get1FLOAT("SELECT commission FROM ats_sysdb.agencydetails")[0]));
            
            
            
            this.commisionProcent.selectAll();
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_commisionProcentFocusGained

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void amount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount2ActionPerformed

    private void returnBlanks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBlanks2ActionPerformed
        try {
            
            
            
            db.statement("UPDATE `ats_sysdb`.`agencydetails` SET `local_currency`='"+amount2.getText()+"' ");
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_returnBlanks2ActionPerformed

    private void returnBlanks3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBlanks3ActionPerformed
        // TODO add your handling code here:
        
        try {
            

            db.statement("UPDATE `ats_sysdb`.`agencydetails` SET `exchange_rate`='"+amount3.getText()+"'");
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_returnBlanks3ActionPerformed

    private void amount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount3ActionPerformed

    private void genAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genAlertActionPerformed
        // TODO add your handling code here:
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyHHmm");
            LocalDateTime localDate = LocalDateTime.now();
        
        try{
            
            PrintWriter writer = new PrintWriter("Alert_"+(String)table.getModel().getValueAt(table.getSelectedRow(), 0)+"_"+dtf.format(localDate)+".txt", "UTF-8");
            String name=(String)table.getModel().getValueAt(table.getSelectedRow(), 0);
            float amn=(float)table.getModel().getValueAt(table.getSelectedRow(), 2);
            String dt=(String)table.getModel().getValueAt(table.getSelectedRow(), 1);
            
            String curr = db.get1String("SELECT local_currency FROM ats_sysdb.agencydetails")[0];
            writer.print(name+", please pay the remaining amount of "+amn+" "+curr+". Please pay within a month of purchase date ("+dt+")");
            writer.close();
            
        } catch (IOException e) {
                // do something
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_genAlertActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        ATSFrontEnd.visi();
    }//GEN-LAST:event_logOutActionPerformed

    private void manageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersActionPerformed
        // TODO add your handling code here:
        
        ManageCustomersGUI r = new ManageCustomersGUI(true);
        r.setVisible(true);
        
    }//GEN-LAST:event_manageCustomersActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        try {
            
            String[] a =db.get1String("SELECT idcustomer FROM ats_sysdb.transaction WHERE amount>paid");
            float[] b =db.get1FLOAT("SELECT amount FROM ats_sysdb.transaction WHERE amount>paid");
            float[] c =db.get1FLOAT("SELECT paid FROM ats_sysdb.transaction WHERE amount>paid");
            String[] d =db.get1String("SELECT date FROM ats_sysdb.transaction WHERE amount>paid");
            
            
            
            int i=0;
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            int rowCount = model.getRowCount();

            for (int x = rowCount - 1; x >= 0; x--) 
                model.removeRow(i);
            
            while(a[i]!=null)
            {
                String cln = db.get1String("SELECT firstname FROM ats_sysdb.customer WHERE passportno = "+a[i]+"")[0]+ " "+ db.get1String("SELECT lastname FROM ats_sysdb.customer WHERE passportno = "+a[i]+"")[0];
                model.addRow(new Object[]{ cln , d[i] , b[i]-c[i] });
                //userTable.getModel().setValueAt(s[i],i,0);
                //userTable.getModel().setValueAt(n[i],i,1);
                //userTable.getModel().setValueAt(r[i],i,2);
                i++;
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void setCommisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCommisionActionPerformed
        try {
            

            db.statement("UPDATE `ats_sysdb`.`agencydetails` SET `commission`='"+commisionProcent.getText()+"'");
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_setCommisionActionPerformed

    private void amount2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amount2FocusGained
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            
            amount2.setText(db.get1String("SELECT local_currency FROM ats_sysdb.agencydetails")[0]);
            
            
            
            this.amount2.selectAll();
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_amount2FocusGained

    private void amount3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amount3FocusGained
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            
            amount3.setText(Float.toString(db.get1FLOAT("SELECT exchange_rate FROM ats_sysdb.agencydetails")[0]));
            
            
            
            this.amount3.selectAll();
        } catch (SQLException ex) {
            Logger.getLogger(OfficeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_amount3FocusGained

    private void stockReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockReportActionPerformed
        // TODO add your handling code here:
        ATSReportView r = new ATSReportView(0);
        r.setVisible(true);
        
        
    }//GEN-LAST:event_stockReportActionPerformed

    private void returnBlanksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBlanksActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //db.statement("DELETE FROM `ats_sysdb`.`blank` WHERE `idblank` LIKE '___"+String.format("%04d", Integer.parseInt(blankAmount1.getText()))+"____'");
            db.statement("UPDATE `ats_sysdb`.`blank` SET `void`='1' WHERE `idblank` LIKE '___"+String.format("%04d", Integer.parseInt(amount.getText()))+"____'");
            //int nr =db.get1INT("SELECT lateststock FROM ats_sysdb.agencydetails WHERE `name`='ATS'")[0]-1;
            //db.statement("UPDATE `ats_sysdb`.`agencydetails` SET `lateststock`='"+nr+"' WHERE `name`='ATS'");
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_returnBlanksActionPerformed

    private void amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusGained
        // TODO add your handling code here:
        
        this.amount.selectAll();
    }//GEN-LAST:event_amountFocusGained

    private void blankSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blankSearchActionPerformed
        // TODO add your handling code here:
        
        ManageBlanks r = new ManageBlanks();
        r.setVisible(true);
        
    }//GEN-LAST:event_blankSearchActionPerformed

    private void clientNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientNameFocusGained
        // TODO add your handling code here:
        this.clientName.selectAll();
    }//GEN-LAST:event_clientNameFocusGained

    private void clientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNameActionPerformed

    private void clientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientReportActionPerformed
        // TODO add your handling code here:
        String cname=clientName.getText();
        ATSReportView r = new ATSReportView(6,cname);
        r.setVisible(true);
        
    }//GEN-LAST:event_clientReportActionPerformed

    private void domReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domReportActionPerformed
        // TODO add your handling code here:
        ATSReportView r = new ATSReportView(3);
        r.setVisible(true);
        
    }//GEN-LAST:event_domReportActionPerformed

    private void interReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interReportActionPerformed
        // TODO add your handling code here:
        
        ATSReportView r = new ATSReportView(4);
        r.setVisible(true);
        
    }//GEN-LAST:event_interReportActionPerformed

    private void discountRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountRepoActionPerformed
        // TODO add your handling code here:
        
        ATSReportView r = new ATSReportView(5);
        r.setVisible(true);
    }//GEN-LAST:event_discountRepoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount2;
    private javax.swing.JTextField amount3;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountLabel1;
    private javax.swing.JLabel amountLabel2;
    private javax.swing.JLabel amountLabel4;
    private javax.swing.JButton blankSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField clientName;
    private javax.swing.JButton clientReport;
    private javax.swing.JTextField commisionProcent;
    private javax.swing.JButton discountRepo;
    private javax.swing.JButton domReport;
    private javax.swing.JButton genAlert;
    private javax.swing.JButton interReport;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton manageCustomers;
    private javax.swing.JLabel procentLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton returnBlanks;
    private javax.swing.JButton returnBlanks2;
    private javax.swing.JButton returnBlanks3;
    private javax.swing.JButton setCommision;
    private javax.swing.JButton stockReport;
    private javax.swing.JTable table;
    private javax.swing.JLabel typeLabel1;
    // End of variables declaration//GEN-END:variables
}
